# Note to self: the source of truth for this file is at
# https://github.com/SidneyBovet/games_database_docker/blob/master/Dockerfile
services:
  web:
    build: .
    volumes:
      - .:/app
    # Installed by the Dockerfile:
    command: screen-server -c rpi-screen-service/config.json -l rpi-screen-service/log4rs_config.yml
    ports:
      - "26652:26652/tcp"
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://cdn3.iconfinder.com/data/icons/electrical-components/100/feb-elecomp-go-17-512.png'
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
